// igui-app/src/adapters/input/ui/react-app/src/App.tsx
import React, { useState } from 'react';

export default function App() {
  const [text, setText] = useState('');
  const [result, setResult] = useState('');

  const translate = async () => {
    const resp = await fetch('http://localhost:3000/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, fromLang: 'spanish', toLang: 'english' })
    });
    const data = await resp.json();
    setResult(data.translated);
  };

  return (
    <div style={{ padding: 20 }}>
      <h1>Traductor Hexagonal (React + Vite)</h1>
      <textarea rows={6} cols={80} value={text} onChange={e=>setText(e.target.value)} placeholder="Escribe texto en español..." />
      <div style={{ marginTop: 10 }}>
        <button onClick={translate}>Traducir</button>
      </div>
      <pre style={{ whiteSpace: 'pre-wrap' }}>{result}</pre>
    </div>
  );
}

// igui-hexagonal/src/adapters/input/ui/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { Container } from '../../../../config/container';

@Component({
  selector: 'app-root',
  template: `
    <div style="padding:20px">
      <h1>Traductor Hexagonal (Angular)</h1>
      <textarea [(ngModel)]="text" rows="4" cols="50" placeholder="Escribe texto en español..."></textarea>
      <div style="margin-top:10px">
        <button (click)="translate()">Traducir</button>
      </div>
      <p style="white-space: pre-wrap">{{ result }}</p>
    </div>
  `
})
export class AppComponent {
  text = '';
  result = '';

  async translate() {
    const svc = Container.getTranslateService();
    const words = this.text.trim().split(/\s+/);
    const res = await svc.translateArray(words, 'spanish', 'english');
    this.result = res.join(' ');
  }
}
