// igui-hexagonal/src/adapters/input/ui/react-app/src/App.tsx
import React, { useState } from "react";
import { Container } from "../../../../config/container";

export default function App() {
  const [text, setText] = useState(""); 
  const [result, setResult] = useState(""); 

  const handle = async () => {
    const svc = Container.getTranslateService();
    const words = text.trim().split(/\s+/);
    const res = await svc.translateArray(words, 'spanish', 'english');
    setResult(res.join(' '));
  };

  return (
    <div style={{ padding: 20 }}>
      <h1>Traductor Hexagonal (React)</h1>
      <textarea value={text} onChange={e => setText(e.target.value)} rows={4} cols={50} placeholder="Escribe texto en español..." />
      <div style={{ marginTop: 10 }}>
        <button onClick={handle}>Traducir</button>
      </div>
      <p style={{ whiteSpace: 'pre-wrap' }}>{result}</p>
    </div>
  );
}

// igui-hexagonal/src/adapters/input/ui/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { Container } from '../../../../config/container';

@Component({
  selector: 'app-root',
  template: `
    <div style="padding:20px">
      <h1>Traductor Hexagonal (Angular)</h1>
      <textarea [(ngModel)]="text" rows="4" cols="50" placeholder="Escribe texto en español..."></textarea>
      <div style="margin-top:10px">
        <button (click)="translate()">Traducir</button>
      </div>
      <p style="white-space: pre-wrap">{{ result }}</p>
    </div>
  `
})
export class AppComponent {
  text = '';
  result = '';

  async translate() {
    const svc = Container.getTranslateService();
    const words = this.text.trim().split(/\s+/);
    const res = await svc.translateArray(words, 'spanish', 'english');
    this.result = res.join(' ');
  }
}
