// igui/src/ui/react-app/src/App.tsx
import React, { useState } from "react";
import { TranslateWord } from "../../../core/application/TranslateWord";
import { FakeTranslatorAdapter } from "../../../infrastructure/FakeTranslatorAdapter";
import { ApiTranslatorAdapter } from "../../../infrastructure/ApiTranslatorAdapter";

export default function App() {
  const [word, setWord] = useState("");
  const [result, setResult] = useState("");
  const [useApi, setUseApi] = useState(false);

  const handleTranslate = async () => {
    const translator = useApi ? new ApiTranslatorAdapter() : new FakeTranslatorAdapter();
    const useCase = new TranslateWord(translator);
    setResult(await useCase.execute(word, "es", "en"));
  };

  return (
    <div>
      <h1>React Traductor</h1>
      <input
        value={word}
        onChange={e => setWord(e.target.value)}
        placeholder="Escribe una palabra..."
      />
      <label>
        <input
          type="checkbox"
          checked={useApi}
          onChange={() => setUseApi(!useApi)}
        />
        Usar API real
      </label>
      <button onClick={handleTranslate}>Traducir</button>
      <p>{result}</p>
    </div>
  );
}

// igui/src/ui/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { TranslateWord } from '../../../../core/application/TranslateWord';
import { FakeTranslatorAdapter } from '../../../../infrastructure/FakeTranslatorAdapter';
import { ApiTranslatorAdapter } from '../../../../infrastructure/ApiTranslatorAdapter';

@Component({
  selector: 'app-root',
  template: `
    <h1>Angular Traductor</h1>
    <input [(ngModel)]="word" placeholder="Escribe una palabra..." />
    <label>
      <input type="checkbox" [(ngModel)]="useApi" />
      Usar API real
    </label>
    <button (click)="translate()">Traducir</button>
    <p>{{ result }}</p>
  `
})
export class AppComponent {
  word = '';
  result = '';
  useApi = false;

  async translate() {
    const translator = this.useApi ? new ApiTranslatorAdapter() : new FakeTranslatorAdapter();
    const useCase = new TranslateWord(translator);
    this.result = await useCase.execute(this.word, 'es', 'en');
  }
}
